#!/usr/bin/env python3
"""PostToolUse tripwire: flag caveman-rule violations in comments model just
wrote. Marker per file type -- ``//`` for ``.go``, ``#`` for ``.py``, ``.sh``,
``.bash`` and extension-less files under ``.githooks/``.

Go doc comments get linted like any other comment: user-facing prose live in
strings, not in comments, so nothing here is exempt.

Line-based split, so marker inside string literal is guarded by quote balance
only -- best-effort, tripwire not parser. Exit 2 with stderr feeds finding back
to model so it self-corrects; never blocks edit (tool already ran).
"""

from __future__ import annotations

import json
import re
import sys

_SLASH = "//"
_HASH = "#"

_EXT_MARKER = {
    ".go": _SLASH,
    ".py": _HASH,
    ".sh": _HASH,
    ".bash": _HASH,
}
# Git hooks carry no extension; shell comment syntax regardless of interpreter.
_HASH_DIR = "/.githooks/"

# Functional pseudo-comments drive tooling -- never lint prose after them.
_FUNCTIONAL = {
    _HASH: re.compile(
        r"#\s*(noqa|type:\s*ignore|pragma|fmt:|ruff:|isort:|coding:|shellcheck|!)"
    ),
    _SLASH: re.compile(
        r"//\s*(go:|nolint|lint:ignore|\+build|Code generated by)",
    ),
}

# whole-word, case-insensitive where prose varies. ``a`` left out on purpose:
# one-letter match fire on prose that read fine, same call as polarion hook.
_ARTICLE = re.compile(r"\b(the|an)\b", re.IGNORECASE)
_FILLER = re.compile(
    r"\b(just|really|basically|actually|simply|of course|please)\b",
    re.IGNORECASE,
)


def _marker_rules(marker: str) -> dict[str, re.Pattern[str]]:
    """Per-marker patterns for rules that anchor on comment opener."""
    m = re.escape(marker)
    return {
        # caveman bans leading NOTE / WARNING prefixes + banner dividers.
        "prefix": re.compile(rf"{m}\s*(WARNING|NOTE)\b", re.IGNORECASE),
        "banner": re.compile(rf"{m}\s*[=\-*_]{{4,}}"),
        # task-marker without ``(owner/#issue)`` = stray.
        "stray_todo": re.compile(rf"{m}.*\bTODO\b(?!\s*\()"),
    }


_RULES = {marker: _marker_rules(marker) for marker in (_HASH, _SLASH)}


def _marker_for(path: str) -> str | None:
    """Comment marker to scan for in ``path``, or None when out of scope."""
    if not isinstance(path, str) or not path:
        return None
    if _HASH_DIR in path or path.startswith(".githooks/"):
        return _HASH
    for ext, marker in _EXT_MARKER.items():
        if path.endswith(ext):
            return marker
    return None


def _comment_text(line: str, marker: str) -> str | None:
    """Return comment portion of line, or None. Naive split: skip lines where
    marker sits inside string literal (best-effort).
    """
    idx = line.find(marker)
    if idx == -1:
        return None
    before = line[:idx]
    # crude string guard: unbalanced quote before marker = likely inside.
    if before.count('"') % 2 or before.count("'") % 2 or before.count("`") % 2:
        return None
    return line[idx:]


def _scan(text: str, marker: str | None) -> list[str]:
    if marker is None:
        return []
    rules = _RULES[marker]
    findings: list[str] = []
    for raw in text.splitlines():
        comment = _comment_text(raw, marker)
        if comment is None or _FUNCTIONAL[marker].search(comment):
            continue
        body = comment.lstrip(marker[0]).strip()
        if not body:
            continue
        if _ARTICLE.search(body):
            findings.append(f'article: "{body}"')
        if _FILLER.search(body):
            findings.append(f'filler: "{body}"')
        if rules["prefix"].search(comment):
            findings.append(f'NOTE/WARNING prefix: "{body}"')
        if rules["banner"].search(comment):
            findings.append(f'banner divider: "{body}"')
        if rules["stray_todo"].search(comment):
            findings.append(f'stray TODO (need owner/#issue): "{body}"')
    return findings


def _edited_text(tool_input: dict[str, object]) -> str:
    """Concatenate new comment-bearing text from Edit/Write/MultiEdit input."""
    parts: list[str] = []
    for key in ("new_string", "content"):
        val = tool_input.get(key)
        if isinstance(val, str):
            parts.append(val)
    edits = tool_input.get("edits")
    if isinstance(edits, list):
        for e in edits:
            if isinstance(e, dict) and isinstance(e.get("new_string"), str):
                parts.append(e["new_string"])
    return "\n".join(parts)


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0
    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        return 0
    path = tool_input.get("file_path", "")
    marker = _marker_for(path)
    if marker is None:
        return 0

    findings = _scan(_edited_text(tool_input), marker)
    if not findings:
        return 0

    # dedup, keep order.
    seen: dict[str, None] = {}
    for f in findings:
        seen.setdefault(f, None)
    msg = "\n".join(f"  - {f}" for f in seen)
    print(
        "Comment-style tripwire (caveman rules) in "
        f"{path}:\n{msg}\n"
        "Drop articles/filler, no NOTE:/WARNING:/banner, TODO needs "
        "(owner/#issue). Fix these comments. (User-facing prose live in "
        "strings, not comments -- nothing here is exempt.)",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
